version: '3.7'

services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: .
      dockerfile: ./docker/Dockerfile
    image: pingcrm/php:8.1
    container_name: '${APP_CONTAINER:-app}_APP'
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  server:
    image: nginx:alpine
    container_name: '${APP_CONTAINER:-app}_SERVER'
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT:-80}:80"
      - "${APP_PORT_HTTPS:-433}:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - '6432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
